name: "Check Python source distribution"
author: "Casper Welzel Andersen"
description: "Make sure a Python source distribution is buildable and installable."

branding:
  icon: box
  color: orange

inputs:
  repository:
    description: "Repository for which to check building and installation of the source distribution."
    required: false
    default: ""
  token:
    description: "Token with which to retrieve `repository`."
    required: false
    default: ""

runs:
  using: docker
  image: Dockerfile
