name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  repository:
    runs-on: ubuntu-latest
    name: Test `repository`

    steps:
    - name: Option 2 - Checkout this repository
      uses: actions/checkout@v2

    - name: Build and install 'good' test package
      uses: ./
      with:
        repository: CasperWA/check-sdist-action
        branch: CI-test_good_package

  repository_token:
    runs-on: ubuntu-latest
    name: Test `repository` and `token`

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Build and install 'good' test package (using GITHUB_TOKEN)
      uses: ./
      with:
        repository: CasperWA/push-protected
        branch: CI-test_good_package
        token: ${{ secrets.GITHUB_TOKEN }}

  fail_bad_package:
    runs-on: ubuntu-latest
    name: Test action fails for 'bad' package

    steps:
    - name: Option 2 - Checkout this repository
      uses: actions/checkout@v2

    - name: Build and install 'bad' test package
      uses: ./
      with:
        repository: CasperWA/check-sdist-action
        branch: CI-test_bad_package
