name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  repository:
    runs-on: ubuntu-latest
    name: Option 2 - Test `repository`

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Build and install 'CasperWA/push-protected'
      uses: ./
      with:
        repository: CasperWA/push-protected

  repository_token:
    runs-on: ubuntu-latest
    name: Option 2 - Test `repository` and `token`

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Build and install 'CasperWA/push-protected' (using GITHUB_TOKEN)
      uses: ./
      with:
        repository: CasperWA/push-protected
        token: ${{ secrets.GITHUB_TOKEN }}
