name: Release - updating vMAJOR tag

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'CasperWA/check-sdist-action' && startsWith(github.ref, 'refs/tags/v')
    env:
      PUBLISH_UPDATE_BRANCH: main

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update tags (and possibly the README)
      run: .github/static/update_version.sh

    - name: Push updates to '${{ env.PUBLISH_UPDATE_BRANCH }}'
      uses: ./
      with:
        token: ${{ secrets.RELEASE_PAT }}
        branch: ${{ env.PUBLISH_UPDATE_BRANCH }}
        force: true
        tags: true
